### ISSUE TITLE
Costos y Juicio Exp

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-reciclaenexus#1]
[Costos y Juicio Exp.pdf](https://github.com/user-attachments/files/17547601/Costos.y.Juicio.Exp.pdf)

**Comment by josealfredo79** [comment]
Calificacion..???

**Comment by ToniDepp** [comment]
**Portada:** Cuenta con todos los elementos 25/25
**Procedimiento:** Describe bien los procesos y le da un enfoque a cada uno 25/25
**Figuras, ilustraciones y fotografías:** 25/ 25
**Resultados y conclusión:** Muy resumido, pero está bien 25/25
**Puntos:** 100/100
**Calificación final:** 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
